### PR TITLE
fix rotation and camera for w7

### PR DESCRIPTION
**Pull request by mosimchah**

### CODE REVIEW

**Comment by Quarx2k** [comment]
Contain a lot of duplicate files in lib, vendor/lib

**Comment by MobiusM** [comment]
@mosimchah if you want this to be merged, you need to clean it up...

**Comment by Quarx2k** [comment]
Remove also duplicate files, not only from config.

**Comment by mosimchah** [comment]
not needed https://github.com/TheMuppets/proprietary_vendor_lge/pull/288

**Pull request closed without merging**
