### PR TITLE
Add msm8226 devices family

### PR DESCRIPTION
**Pull request by Quarx2k**
L70, L90, G2Mini, G3s 3g, G3s lte
Also mail on abhisek@cyngn.com and devrel@cyanogenmod.org

### CODE REVIEW

**Comment by Quarx2k** [comment]
Anyone? :( @intervigilium @ciwrl

**Comment by nikich340** [comment]
Devs, where are you? @intervigilium @ciwrl

**Comment by vm03** [comment]
Please don't be silent. CyanogenMOD is community or only corp now?

**Comment by dmboev** [comment]
Devs?We need your support=(

**Comment by Vule991** [comment]
Developers have made a great effort on this project, please reward it. @ciwrl @intervigilium

**Pull request merged**
