### PR TITLE
cm-14.1_gps_modem_power_voting

### PR DESCRIPTION
**Pull request by Kasual**
ls990: Regenerate makefiles to fix build

Change-Id: Ia4fb7d10c530d998e87a4aeb606cfbe725377c2d

### CODE REVIEW

**Comment by invisiblek** [comment]
@Shelnutt2 good with this?

**Comment by Shelnutt2** [comment]
When did the builds break? Things were compiling fine before the rebranding.

**Comment by Kasual** [comment]
After this was merged I ran into the build error https://review.lineageos.org/#/c/154028/

**Comment by Shelnutt2** [comment]
lgtm

**Pull request merged**
