### PR TITLE
msm8996: Update vulkan libs from oneplus/cheeseburger

### PR DESCRIPTION
**Pull request by ghost**
* Vulkan is otherwise broken in 14.1, tested on the G5
* Previously omitted from graphics blobs update in a849224739b7d59052a59cbe67c669b9504ef986

### CODE REVIEW

**Comment by Rashed97** [comment]
Where did you get these from? Cheeseburger is 8998

**Comment by ghost** [comment]
> Where did you get these from? Cheeseburger is 8998

I just renamed the 8998 files. I read from some hacky attempts at moving vulkan to unsupported devices that this tends to work (e.g. 8994 -> 8992). 

I was also confused as to why you pulled blobs from cheeseburger in the first place. But I can't argue with the results; reverting to the blobs from LA.UM.5.5.r1-02500-8x96.0 that most other 8996 devices use caused scroll lag and performance issues. But the currently mismatched vulkan doesn't work.

**Comment by Rashed97** [comment]
Why? Because if you look at the device trees, we're using the 8998 display and media HALs. Also cm-14.1 is no longer being actively developed for LG 8996 devices as all development has moved to 15.1

**Comment by ghost** [comment]
That's fine. Weekly builds for these devices are still on 14.1, so I figured I'd push this change. If there's no interest in it, I'll just close it.

**Pull request closed without merging**
