### PR TITLE
add thunderg (LG P500) proprietaries

### PR DESCRIPTION
**Pull request by mik9**

### CODE REVIEW

**Comment by mik9** [comment]
Please add [android_device_lge_thunderg](https://github.com/CyanogenMod/android_device_lge_thunderg) to gerrit projects.

**Comment by koush** [comment]
Is thunderg ready for merging then? Does everything work?

**Comment by mik9** [comment]
Yes, current buglist:
1. Camera zoom does not works.
2. Bluetooth calls does nit works.
Everything else works fine.
There are few open commits in gerrit from me (Kiril Mikos).
On Jun 22, 2011 7:52 PM, "koush" <
reply@reply.github.com>
wrote:

**Comment by inferiorhumanorgans** [comment]
The camera zoom didn't work on my OV because a few fields in the common_crop_t and cam_ctrl_dimension_t structs were in the wrong order.  You can verify this by looking at the preview width/height (they're likely inverted in the EXIF data too).  I fixed this with inferiorhumanorgans/android_device_lge_thunderc@ec54c40, dunno if it'll apply cleanly to your branch but you can get the gist of it.  With my phone, at least, there are a few other weird camera glitches.

Also, wired headset audio doesn't work for phone calls either.  I expect that's a common bug with the P500.

**Pull request merged**
