### PR TITLE
mako: update blobs to LMY48M

### PR DESCRIPTION
**Pull request by liquid64**
updating mako blobs to LMY48M

### CODE REVIEW

**Comment by Haifen** [comment]
The binary blobs for Mako in this repository are now 4 releases old.  I've been manually updating blobs in my local repo, but I strongly recommend merging liquid64's pull request, since I'm OK with making changes in a local_blobs_cm-12.1 branch in my repo, but not everyone might be, and while I've compiled ROMs with updated binaries that worked OK, I trust liquid64's ability to have the three archive files migrated into proprietary_vendor_lge much more than I trust my own.

**Comment by Haifen** [comment]
Put another way:  I used liquid64's commits as a reference to see what I did wrong.  I applied the requisite fixes personally, and git diff local_blobs_cm-12.1 liquid64_cm-12.1 now returns 0.  I'm **still** going with liquid64's branch for builds.

If that sounds too much like the [Knight and The LISP Machine AI Koan](http://www.catb.org/jargon/html/koans.html#id3141171), tough.

**Comment by liquid64** [comment]
Thanks for the vote of confidence.  I don't know if there is a better way of doing it, but basically, I downloaded all 3 of the LMY48M blob packages from https://developers.google.com/android/nexus/drivers. I then used a perl script that I wrote, to parse the device-partial.mk files in each download, to determine where each file should go.  I have found that it works great, except for one file "libacdbloader.so", which isn't referenced in qcom's device-partial.mk file, like everything else is.  I'm still learning, so if there is a more standard/proven way, I'd love to learn more.

Anyway, I too have been testing these blobs for a while (along with LMY48I and LMY47V), and they have all been daily drivers for me.

**Comment by sysxda** [comment]
Please merge this

**Pull request closed without merging**
