### PR TITLE
h850: Add some camera libs

### PR DESCRIPTION
**Pull request by OwnDroid**
this fixes the issues where users cannot save their videos on all LOS based build

Signed-off-by: OwnDroid <owndroid26@gmail.com>

### CODE REVIEW

**Comment by Rashed97** [comment]
No... Just no.
1) Why are you importing OnePlus camera blobs? We don't use any OnePlus camera blobs.
2) I don't see any reason why this would fix video recording
3) You're not even including these binaries in the makefiles
4) Why are you pushing stuff to just h850? All of the camera stuff is in msm8996-common on g5-common

**Comment by OwnDroid** [comment]
These where not op specific, just forgot to rename them properly I see, also the the binaries where added in the make files of the device common trees, they will be pushed to lineage...
But they certainly fixed the issue as I tested it myself...

**Comment by Rashed97** [comment]
You can't just rename blobs. They're referenced in other blobs by name. Changing their name means they can't be dlopened

**Comment by OwnDroid** [comment]
I agree with you, but I'm 100% sure they fix the issue, so someone can at least take the effort to look into this... It helps a lot of users...

**Comment by Rashed97** [comment]
I'll look into it as soon as I get home. At the mall with a friend atm

**Comment by OwnDroid** [comment]
Great thanks

**Pull request closed without merging**
